name: QuixLake Timeseries sink
language: python
variables:
  - name: input
    inputType: InputTopic
    description: Name of the input topic to listen to.
    defaultValue: config-enriched-data
  - name: input
    inputType: InputTopic
    description: Name of the Kafka input topic to consume from
    required: true
    value: config-enriched-data
  - name: S3_BUCKET
    inputType: FreeText
    description: S3 bucket name for storing Parquet files
    required: true
    value: quixdatalaketest
  - name: S3_PREFIX
    inputType: FreeText
    description: S3 prefix/path for data files
    value: ts_test
  - name: TABLE_NAME
    inputType: FreeText
    description: Table name for data organization and registration
    value: test_runs
  - name: HIVE_COLUMNS
    inputType: FreeText
    description: Comma-separated list of columns for Hive partitioning. Include year/month/day/hour to extract from TIMESTAMP_COLUMN (e.g., location,year,month,day,sensor_type)
    value: campaign_id,environment_id,test_id
  - name: TIMESTAMP_COLUMN
    inputType: FreeText
    description: Column containing timestamp values to extract year/month/day/hour from
    value: kafka_timestamp
  - name: CATALOG_URL
    inputType: FreeText
    description: REST Catalog URL for optional table registration (leave empty to skip)
    value: https://iceberg-catalog-quixers-testrigdemodatawarehouse-prod.az-france-0.app.quix.io
  - name: CATALOG_AUTH_TOKEN
    inputType: Secret
    description: auth token for catalog
    secretKey: quixlake_sdk_token
  - name: AUTO_DISCOVER
    inputType: FreeText
    description: Automatically register table in REST Catalog on first write
    value: true
  - name: CATALOG_NAMESPACE
    inputType: FreeText
    description: Catalog namespace for table registration
    value: default
  - name: BATCH_SIZE
    inputType: FreeText
    description: Number of messages to batch before writing to S3
    value: 1000
  - name: COMMIT_INTERVAL
    inputType: FreeText
    description: Kafka commit interval in seconds
    value: 30
  - name: CONSUMER_GROUP
    inputType: FreeText
    description: Kafka consumer group name
    value: aws_sink_v1
  - name: AUTO_OFFSET_RESET
    inputType: FreeText
    description: Where to start consuming if no offset exists
    value: earliest
  - name: AWS_ACCESS_KEY_ID
    inputType: Secret
    description: AWS Access Key ID for S3 access
    secretKey: aws_access_key
  - name: AWS_SECRET_ACCESS_KEY
    inputType: Secret
    description: AWS Secret Access Key for S3 access
    secretKey: aws_secret_key
  - name: AWS_REGION
    inputType: FreeText
    description: AWS region for S3 bucket
    value: eu-west-2
  - name: LOGLEVEL
    inputType: FreeText
    description: loglevel
    value: INFO
dockerfile: dockerfile
runEntryPoint: dockerfile
defaultFile: dockerfile
libraryItemId: starter-destination
