name: QuixLake Timeseries sink
language: python
variables:
  - name: input
    inputType: InputTopic
    description: Name of the input topic to listen to.
    defaultValue: config-enriched-data
dockerfile: dockerfile
runEntryPoint: dockerfile
defaultFile: dockerfile
libraryItemId: starter-destination
