name: MQTT Source Exotic
language: python
variables:
  - name: output
    inputType: OutputTopic
    description: Name of the output topic to publish to.
    required: true
  - name: mqtt_topic
    inputType: FreeText
    description: The root for messages in MQTT, this can be anything
    defaultValue: '#'
    required: true
  - name: mqtt_server
    inputType: FreeText
    description: The address of your MQTT server
    required: true
  - name: mqtt_port
    inputType: FreeText
    description: The port of your MQTT server
    defaultValue: 8883
    required: true
  - name: mqtt_username
    inputType: FreeText
    description: Username of your MQTT user
  - name: mqtt_password
    inputType: Secret
    description: Password for the MQTT user
  - name: mqtt_version
    inputType: FreeText
    description: 'MQTT protocol version: 3.1, 3.1.1, 5'
    defaultValue: 3.1.1
    required: true
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: mqtt_function.py
libraryItemId: mqtt-source
